### ISSUE TITLE
Add Authentication Check

### ISSUE THREAD

**Issue by flamespinner** [CalicoCountyRP/calico_core#1]
Create an authentication check to make sure a user is logged in via discord, if they are not, redirect to "/".

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added an authentication check in the frontend to ensure users are logged in via Discord. If not logged in, they are redirected to the home page. Also added a new route in the backend to check authentication status.

You can review changes in this commit: https://github.com/mnmnk43434/flamespinner-calico_core-1/commit/8afc651154af849cc2f962a9cc42b567aa004673.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
